services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - devbarber_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7
    container_name: redis-nest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  devbarber_pgdata:
  redis_data:
